[package]
name = "ratatui-system-monitor"
version = "0.1.0"
description = "system monitoring program like htop"
authors = ["Knotty123230 <taranenkovo03@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
sysinfo = {version = "0.35.2" ,features = ["serde"]}
serde_json = "1.0.141"
